[settings]
experimental = true

[tools]
"aqua:hashicorp/terraform" = "1.15.6"
"aqua:aquasecurity/trivy" = "0.70.0"
"aqua:terraform-docs/terraform-docs" = "0.24.0"
"aqua:pre-commit/pre-commit" = "4.6.0"
tflint = "latest"
